### ISSUE TITLE
test time::time_point::tests::time_point_creation panicks on i386

### ISSUE THREAD

**Issue by jonassmedegaard** [gwen-lg/subtile#4]
subtile v0.1.8 panicks the test time::time_point::tests::time_point_creation on i386 architecture:
```
123s test time::time_point::tests::time_point_creation ... FAILED
123s 
123s failures:
123s 
123s ---- time::time_point::tests::time_point_creation stdout ----
123s thread 'time::time_point::tests::time_point_creation' panicked at src/time/time_point.rs:84:9:
123s assertion `left == right` failed
123s   left: TimePoint(142)
123s  right: TimePoint(141)
123s stack backtrace:
123s    0: rust_begin_unwind
123s              at /usr/src/rustc-1.74.1/library/std/src/panicking.rs:597:5
123s    1: core::panicking::panic_fmt
123s              at /usr/src/rustc-1.74.1/library/core/src/panicking.rs:72:14
123s    2: core::panicking::assert_failed_inner
123s    3: core::panicking::assert_failed
123s              at /usr/src/rustc-1.74.1/library/core/src/panicking.rs:270:5
123s    4: subtile::time::time_point::tests::time_point_creation
123s              at ./src/time/time_point.rs:84:9
123s    5: subtile::time::time_point::tests::time_point_creation::{{closure}}
123s              at ./src/time/time_point.rs:82:30
123s    6: core::ops::function::FnOnce::call_once
123s              at /usr/src/rustc-1.74.1/library/core/src/ops/function.rs:250:5
123s    7: core::ops::function::FnOnce::call_once
123s              at /usr/src/rustc-1.74.1/library/core/src/ops/function.rs:250:5
```

**Comment by gwen-lg** [comment]
I'm surprise by this result.
How 0.142 * 1000.0 can result to 141 ?
Or it's related to cast with `as` ?

can you test with the change in the branch : https://github.com/gwen-lg/subtile/tree/time_point_panic ?

**Comment by jonassmedegaard** [comment]
I am happy to help test, and have now issued an experimental release to Debian with the two patches in that branch applied.
When the various build daemons catch up - within few hours, typically - we will [have the results](https://buildd.debian.org/status/package.php?p=rust-subtile&suite=experimental).

**Comment by jonassmedegaard** [comment]
Correction: Due to how the package is built for Debian, build-daemons for architectures other than amd64 will never try build experimental releases. I have now rereleased for Debian unstable, and results should appear within some ours in the top center part of [the development status page](https://tracker.debian.org/rust-subtile) for the package.

**Comment by gwen-lg** [comment]
@jonassmedegaard I just release a new version of subtile and subtile-ocr with this change and other small improvement.

**Comment by jonassmedegaard** [comment]
Great!

Released [to Debian](https://tracker.debian.org/pkg/rust-subtile) now (only subtile for now - haven't finalized the packaging of subtile-ocr yet).
